#Goal of lab:
1. Generate and manipulate signals
2. Visualize signals
3. Save signals to listen to them 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.io.wavfile as wavfile
#import winsound
#from mlp

In [33]:
'''Create continous time sinusiod'''
def continousTimeSinusoid(A, signal_freq, phase_phi, freq_sampling, start_time, end_time):
    #how do we generate a continous time signal -> this won't be possible as that would mean infinite values
    #this is just the cos / sine function with some phase shift
    #Acos(2*pi*f*t + phi)
    #so we generate the samples we need based on sampling frequency
    time_steps = np.arange(start_time, end_time, 1.0/freq_sampling) #Step size in time duration = 1/sampling frequency
    time_steps = time_steps.reshape(time_steps.shape[0],1)
    sample_step = np.array(range(0, ))
    cont_signal = A*np.cos(2*np.pi*signal_freq*time_steps + phase_phi)
    concatenated_tensor = np.concatenate((time_steps, cont_signal), axis =1)
    return concatenated_tensor

def sketch_signal():
    None

In [34]:
q3_1 = continousTimeSinusoid(10, 1000, 0, 16000, 0, 0.5)

In [35]:
q3_1

array([[  0.00000000e+00,   1.00000000e+01],
       [  6.25000000e-05,   9.23879533e+00],
       [  1.25000000e-04,   7.07106781e+00],
       ..., 
       [  4.99812500e-01,   3.82683432e+00],
       [  4.99875000e-01,   7.07106781e+00],
       [  4.99937500e-01,   9.23879533e+00]])

In [ ]:
def gen_DTMFseq(code, freqs, durTone):
    '''
    A DTMF sequence consists of two frequencies -> dual tone multi frequency
    '''

In [23]:
def gen_discrete_time_polar_signal(A, omega, phase_shift, start_sample_n, end_sample_n):
    '''(Ae^(i(angle)))^n'''
    samples = np.arange(start_sample_n, end_sample_n)
    samples = samples.reshape(samples.shape[0],1)
    
    magnitude = np.power(A, samples)
    exp_real_val = np.cos(omega*samples + phase_shift)#cosine
    exp_img_val = np.sin(omega*samples + phase_shift) #sin
    concatentated_tensor = np.concatenate((samples, magnitude*exp_real_val, magnitude*exp_img_val), axis =1)
    
    #coordinate_tuple = n, magnitude*exp_real_val, magnitude*exp_img_val
    return concatentated_tensor

In [24]:
gen_discrete_time_polar_signal(0.95, np.pi/18, 0, 0, 50)

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  1.00000000e+00,   9.35567365e-01,   1.64965769e-01],
       [  2.00000000e+00,   8.48072590e-01,   3.08673179e-01],
       [  3.00000000e+00,   7.42508531e-01,   4.28687500e-01],
       [  4.00000000e+00,   6.23947987e-01,   5.23554526e-01],
       [  5.00000000e+00,   4.97376799e-01,   5.92750587e-01],
       [  6.00000000e+00,   3.67545945e-01,   6.36608251e-01],
       [  7.00000000e+00,   2.38845422e-01,   6.56222404e-01],
       [  8.00000000e+00,   1.15201749e-01,   6.53341584e-01],
       [  9.00000000e+00,   3.85916461e-17,   6.30249410e-01],
       [  1.00000000e+01,  -1.03969578e-01,   5.89640780e-01],
       [  1.10000000e+01,  -1.94541089e-01,   5.34497249e-01],
       [  1.20000000e+01,  -2.70180044e-01,   4.67965563e-01],
       [  1.30000000e+01,  -3.29969931e-01,   3.93242850e-01],
       [  1.40000000e+01,  -3.73580708e-01,   3.13471434e-01],
       [  1.50000000e+01,  -4.01221975e-01,   2.3164561

In [21]:
np.concatenate((x, y,z), axis =1)

array([[  1.        ,   3.        ,   0.90929743],
       [  2.        ,   9.        ,  -0.7568025 ],
       [  3.        ,  27.        ,  -0.2794155 ]])

In [29]:
def gen_W_signal(k, start_n, end_n):
    samples = np.arange(start_n, end_n)
    N = samples.shape[0]
    samples = samples.reshape(N,1)
    exp_real_val = np.cos(2*np.pi*k*samples/N)
    exp_img_val = np.sin(2*np.pi*k*samples/N)
    concatenated_tensor = np.concatenate((samples, exp_real_val, exp_img_val), axis =1)
    return concatenated_tensor

In [30]:
gen_W_signal(1, 0, 16)

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  1.00000000e+00,   9.23879533e-01,   3.82683432e-01],
       [  2.00000000e+00,   7.07106781e-01,   7.07106781e-01],
       [  3.00000000e+00,   3.82683432e-01,   9.23879533e-01],
       [  4.00000000e+00,   6.12323400e-17,   1.00000000e+00],
       [  5.00000000e+00,  -3.82683432e-01,   9.23879533e-01],
       [  6.00000000e+00,  -7.07106781e-01,   7.07106781e-01],
       [  7.00000000e+00,  -9.23879533e-01,   3.82683432e-01],
       [  8.00000000e+00,  -1.00000000e+00,   1.22464680e-16],
       [  9.00000000e+00,  -9.23879533e-01,  -3.82683432e-01],
       [  1.00000000e+01,  -7.07106781e-01,  -7.07106781e-01],
       [  1.10000000e+01,  -3.82683432e-01,  -9.23879533e-01],
       [  1.20000000e+01,  -1.83697020e-16,  -1.00000000e+00],
       [  1.30000000e+01,   3.82683432e-01,  -9.23879533e-01],
       [  1.40000000e+01,   7.07106781e-01,  -7.07106781e-01],
       [  1.50000000e+01,   9.23879533e-01,  -3.8268343